openapi: 3.0.3
info:
  title: IOTA REST API
  description: This document describes the upcoming REST API for Hornet and Bee.
  contact:
    email: contact@iota.org
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.0
externalDocs:
  description: Find out more about IOTA
  url: 'https://iota.org'
servers:
  - url: 'http://127.0.0.1:14265'
tags:
  - name: node
    description: Everything about the node itself.
  - name: tangle
    description: Everything about the tangle itself.
  - name: messages
    description: Everything about messages.
  - name: UTXO
    description: Everything about UTXOs.
  - name: milestones
    description: Everything about milestones.

paths:

  '/health':
    get:
      tags:
        - node
      summary: Returns the health of the node.
      description: Returns the health of the node, which can be used for load-balancing or uptime monitoring.
      responses:
        '200':
          description: node is healthy
        '503':
          description: node is not healthy

  '/api/v1/info':
    get:
      tags:
        - node
      summary: Returns information about the node.
      description: Returns information about the node.
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GetInfoResponse'
              examples:
                default:
                  $ref: '#/components/examples/get-info-response-example'
  
  '/api/v1/tips':
    get:
      tags:
        - tangle
      summary: Returns two non-lazy tips.
      description: >-
        Returns two non-lazy tips. In case the node can only provide one tip,
        tip1 and tip2 are identical.
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GetTipsResponse'
              examples:
                Normal:
                  $ref: '#/components/examples/get-tips-response-example-normal'
                Identical Tips:
                  $ref: '#/components/examples/get-tips-response-example-same'
  
  '/api/v1/messages':
    post:
      tags:
        - messages
      summary: Submit a message to the node.
      description: >-
        Submit a message. The node takes care of missing fields and tries to
        build the message. On success, the message will be stored in the Tangle.
        This endpoint will return the identifier of the message.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Message'
            examples:
              default:
                $ref: '#/components/examples/get-message-by-id-data-response-example'
          application/octet-steam:
            schema:
              type: 'string'
              format: binary
              description: "message in raw binary format"
        required: true
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostMessagesResponse'
              examples:
                default:
                  $ref: '#/components/examples/post-messages-response-example'
        '400':
          description: unsuccessful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestErrorResponse'
    get:
      tags:
        - messages
      summary: Filter messages by a matching criteria.
      description: >-
        Search for messages matching the criteria.
      parameters:
        - in: query
          name: index
          schema:
            type: string
          example: someindexkey
          required: true
          description: Indexation key of the message.
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMessagesByIndexResponse'
              examples:
                default:
                  $ref: '#/components/examples/get-messages-by-index-response-example'
        '400':
          description: unsuccessful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestErrorResponse'
  
  '/api/v1/messages/{messageId}':
    get:
      tags:
        - messages
      summary: Returns message metadata by its identifier.
      description: >-
        Find a message by its identifer. This endpoint returns the given message metadata.
      parameters:
        - in: path
          name: messageId
          schema:
            type: string
          example: f532a53545103276b46876c473846d98648ee418468bce76df4868648dd73e5d
          required: true
          description: Identifier of the message.
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMessageMetadataByIdResponse'
              examples:
                New Message:
                  $ref: '#/components/examples/get-message-by-id-response-example-new'
                Solid:
                  $ref: '#/components/examples/get-message-by-id-response-example-solid'
                Included:
                  $ref: '#/components/examples/get-message-by-id-response-example-included'
                Conflicting:
                  $ref: '#/components/examples/get-message-by-id-response-example-conflicting'
        '400':
          description: unsuccessful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestErrorResponse'
        '404':
          description: unsuccessful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundErrorResponse'

  '/api/v1/messages/{messageId}/data':
    get:
      tags:
        - messages
      summary: Returns message data as JSON by its identifier.
      description: >-
        Find a message by its identifer. This endpoint returns the given message as JSON.
      parameters:
        - in: path
          name: messageId
          schema:
            type: string
          example: f532a53545103276b46876c473846d98648ee418468bce76df4868648dd73e5d
          required: true
          description: Identifier of the message.
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMessageByIdDataResponse'
              examples:
                default:
                  $ref: '#/components/examples/get-message-by-id-data-response-example'
                
        '400':
          description: unsuccessful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestErrorResponse'
        '404':
          description: unsuccessful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundErrorResponse'

  '/api/v1/messages/{messageId}/raw':
    get:
      tags:
        - messages
      summary: Returns message raw bytes by its identifier.
      description: >-
        Find a message by its identifer. This endpoint returns the given message raw data.
      parameters:
        - in: path
          name: messageId
          schema:
            type: string
          example: f532a53545103276b46876c473846d98648ee418468bce76df4868648dd73e5d
          required: true
          description: Identifier of the message.
      responses:
        '200':
          description: successful operation
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
              example: '0100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000eb000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000020000016920b176f613ec7be59e68fc68f597eb3393af80f74c7c3db78198147d5f1f92640000000000000000018afe1f314622cc1ef52f16d619d1baccff81816b7e4e35fe268dc247b730acd65d5d2dd3f7df09000000000001000001f7868ab6bb55800b77b8b74191ad8285a9bf428ace579d541fda47661803ff44e0af5c34ad4edf475a01fb46e089a7afcab158b4a0133f32e889083e1c77eef65548933e0c6d2c3b0ac006cd77e77d778bf37b8d38d219fb62a9a2f718d4c9095100000000000000'
        '400':
          description: unsuccessful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestErrorResponse'
        '404':
          description: unsuccessful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundErrorResponse'

  '/api/v1/messages/{messageId}/children':
    get:
      tags:
        - messages
      summary: Returns the list of messages that reference a message by its identifier.
      description: >-
        Find a message by its identifer. This endpoint returns the given message
        including payload.
      parameters:
        - in: path
          name: messageId
          schema:
            type: string
          example: f532a53545103276b46876c473846d98648ee418468bce76df4868648dd73e5d
          required: true
          description: Identifier of the message.
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMessageChildrenResponse'
              examples:
                Children:
                  $ref: '#/components/examples/get-messages-by-index-response-example-children'
                No Children:
                  $ref: '#/components/examples/get-messages-by-index-response-example-nochildren'
        '400':
          description: unsuccessful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestErrorResponse'
        '404':
          description: unsuccessful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundErrorResponse'

  '/api/v1/outputs/{outputId}':
    get:
      tags:
        - UTXO
      summary: Find an output by its identifier.
      description: >-
        Find an output by its identifier.
      parameters:
        - in: path
          name: outputId
          schema:
            type: string
          required: true
          description: >-
            Identifier of the output. An output is identified by the
            concatenation of `transaction_id+output_index`.
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetOutputsByIdResponse'
              examples:
                default:
                  $ref: '#/components/examples/get-outputs-by-id-response-example'
        '400':
          description: unsuccessful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestErrorResponse'
        '404':
          description: unsuccessful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundErrorResponse'

  '/api/v1/addresses/{address}':
    get:
      tags:
        - UTXO
      summary: Get the balance of a given address.
      description: >-
        Get the balance of a given address.
        If count equals maxResults, then there might be more outputs available but those were skipped for performance reasons. User should sweep the address to reduce the amount of outputs.
      parameters:
        - in: path
          name: address
          schema:
            type: string
          example: 7ed3d67fc7b619e72e588f51fef2379e43e6e9a856635843b3f29aa3a3f1f006
          required: true
          description: Address that is referenced by the outputs.
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAddressBalanceResponse'
              examples:
                Normal:
                  $ref: '#/components/examples/get-address-balance-response-example'
                Max Results:
                  $ref: '#/components/examples/get-address-balance-response-example-maxResults'
        '400':
          description: unsuccessful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestErrorResponse'
        '404':
          description: unsuccessful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundErrorResponse'

  '/api/v1/addresses/{address}/outputs':
    get:
      tags:
        - UTXO
      summary: Get all outputs that use a given address.
      description: >-
        Get all outputs that use a given address.
        If count equals maxResults, then there might be more outputs available but those were skipped for performance reasons. User should sweep the address to reduce the amount of outputs.
      parameters:
        - in: path
          name: address
          schema:
            type: string
          example: 7ed3d67fc7b619e72e588f51fef2379e43e6e9a856635843b3f29aa3a3f1f006
          required: true
          description: Address that is referenced by the outputs.
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAddressOutputsResponse'
              examples:
                default:
                  $ref: '#/components/examples/get-address-outputs-response-example'
        '400':
          description: unsuccessful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestErrorResponse'
        '404':
          description: unsuccessful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundErrorResponse'

  '/api/v1/milestones/{index}':
    get:
      tags:
        - milestones
      summary: Get the milestone by the given index.
      description: Get the milestone by the given index.
      parameters:
        - in: path
          name: index
          schema:
            type: number
          example: 154862
          required: true
          description: Index of the milestone.
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMilestoneByIndexResponse'
              examples:
                default:
                  $ref: '#/components/examples/get-milestone-by-index-response-example'
        '400':
          description: unsuccessful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestErrorResponse'
        '404':
          description: unsuccessful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundErrorResponse'

components:
  examples:
  
    'get-info-response-example':
      value:
        data:
          name: Hornet
          version: 0.5.2
          isHealthy: true
          coordinatorPublicKey: cedb6ed996fc9a4e62dd6cb58f09ee3354c5f034f3250bfad9b0481e98cde625
          latestMilestoneMessageId: d97e89e49ed263b763afeda192515fe154ec826ceb92ef08926cd68ec02c9510
          latestMilestoneIndex: 1699556
          solidMilestoneMessageId: 7ed3d67fc7b619e72e588f51fef2379e43e6e9a856635843b3f29aa3a3f1f006
          solidMilestoneIndex: 1699556
          pruningIndex: 1696326
          features:
            - Plugin X
            - Plugin Y

    'get-tips-response-example-normal':
      value:
        data:
          tip1MessageId: f532a53545103276b46876c473846d98648ee418468bce76df4868648dd73e5d
          tip2MessageId: 78d546b46aec4557872139a48f66bc567687e8413578a14323548732358914a2

    'get-tips-response-example-same':
      value:
        data:
          tip1MessageId: f532a53545103276b46876c473846d98648ee418468bce76df4868648dd73e5d
          tip2MessageId: f532a53545103276b46876c473846d98648ee418468bce76df4868648dd73e5d

    'post-messages-response-example':
      value:
        data:
          messageId: 7ed3d67fc7b619e72e588f51fef2379e43e6e9a856635843b3f29aa3a3f1f006

    'get-messages-by-index-response-example':
      value:
        data:
          index: someindexkey
          maxResults: 1000
          count: 2
          messageIds:
            - f532a53545103276b46876c473846d98648ee418468bce76df4868648dd73e5d
            - 7ed3d67fc7b619e72e588f51fef2379e43e6e9a856635843b3f29aa3a3f1f006

    'get-message-by-id-response-example-new':
      value:
        data:
          messageId: f532a53545103276b46876c473846d98648ee418468bce76df4868648dd73e5d
          parent1MessageId: 7ed3d67fc7b619e72e588f51fef2379e43e6e9a856635843b3f29aa3a3f1f006
          parent2MessageId: d97e89e49ed263b763afeda192515fe154ec826ceb92ef08926cd68ec02c9510
          isSolid: false
          referencedByMilestone: null
          shouldPromote: true
          shouldReattach: false

    'get-message-by-id-response-example-solid':
      value:
        data:
          messageId: f532a53545103276b46876c473846d98648ee418468bce76df4868648dd73e5d
          parent1MessageId: 7ed3d67fc7b619e72e588f51fef2379e43e6e9a856635843b3f29aa3a3f1f006
          parent2MessageId: d97e89e49ed263b763afeda192515fe154ec826ceb92ef08926cd68ec02c9510
          isSolid: true
          referencedByMilestone: null
          shouldPromote: false
          shouldReattach: false

    'get-message-by-id-response-example-included':
      value:
        data:
          messageId: f532a53545103276b46876c473846d98648ee418468bce76df4868648dd73e5d
          parent1MessageId: 7ed3d67fc7b619e72e588f51fef2379e43e6e9a856635843b3f29aa3a3f1f006
          parent2MessageId: d97e89e49ed263b763afeda192515fe154ec826ceb92ef08926cd68ec02c9510
          isSolid: true
          referencedByMilestone: 15465
          ledgerInclusionState: included

    'get-message-by-id-response-example-conflicting':
      value:
        messageId: f532a53545103276b46876c473846d98648ee418468bce76df4868648dd73e5d
        parent1MessageId: 7ed3d67fc7b619e72e588f51fef2379e43e6e9a856635843b3f29aa3a3f1f006
        parent2MessageId: d97e89e49ed263b763afeda192515fe154ec826ceb92ef08926cd68ec02c9510
        isSolid: true
        referencedByMilestone: 15465
        ledgerInclusionState: conflicting

    'get-message-by-id-data-response-example':
      value:
        data:
          version: 1
          parent1: '0000000000000000000000000000000000000000000000000000000000000000'
          parent2: '0000000000000000000000000000000000000000000000000000000000000000'
          payload:
            type: 0
            transaction:
              type: 0
              inputs:
                - type: 0
                  transactionId: '0000000000000000000000000000000000000000000000000000000000000000'
                  transactionOutputIndex: 0
              outputs:
                - type: 0
                  address:
                    type: 1
                    address: 6920b176f613ec7be59e68fc68f597eb3393af80f74c7c3db78198147d5f1f92
                  amount: 100
                - type: 0
                  address:
                    type: 1
                    address: 8afe1f314622cc1ef52f16d619d1baccff81816b7e4e35fe268dc247b730acd6
                  amount: 2779530283277661
              payload: null
            unlockBlocks:
              - type: 0
                signature:
                  type: 1
                  publicKey: f7868ab6bb55800b77b8b74191ad8285a9bf428ace579d541fda47661803ff44
                  signature: e0af5c34ad4edf475a01fb46e089a7afcab158b4a0133f32e889083e1c77eef65548933e0c6d2c3b0ac006cd77e77d778bf37b8d38d219fb62a9a2f718d4c909
          nonce: 81

    'get-messages-by-index-response-example-children':
      value:
        data:
          index: "someindex"
          maxResults: 1000
          count: 3
          messageIds:
            - 1c6943b0487c92fd057d4d22ad844cc37ee27fe6fbe88e5ff0d20b2233f75b9d
            - ed3c3f1a319ff4e909cf2771d79fece0ac9bd9fd2ee49ea6c0885c9cb3b1248c
            - 7ed3d67fc7b619e72e588f51fef2379e43e6e9a856635843b3f29aa3a3f1f006
 
    'get-messages-by-index-response-example-nochildren':
      value:
        data:
          index: "otherindex"
          maxResults: 1000
          count: 0
          messageIds: []

    'get-outputs-by-id-response-example':
      value:
        data:
          messageId: ed3c3f1a319ff4e909cf2771d79fece0ac9bd9fd2ee49ea6c0885c9cb3b1248c
          transactionId: 1c6943b0487c92fd057d4d22ad844cc37ee27fe6fbe88e5ff0d20b2233f75b9d
          outputIndex: 3
          isSpent: false
          output:
            type: 0
            address:
              type: 0
              address: 7ed3d67fc7b619e72e588f51fef2379e43e6e9a856635843b3f29aa3a3f1f006
            amount: 1338263

    'get-address-balance-response-example':
      value:
        data:
          address: 7ed3d67fc7b619e72e588f51fef2379e43e6e9a856635843b3f29aa3a3f1f006
          maxResults: 1000
          count: 25
          balance: 1338263

    'get-address-balance-response-example-maxResults':
      value:
        data:
          address: 7ed3d67fc7b619e72e588f51fef2379e43e6e9a856635843b3f29aa3a3f1f006
          maxResults: 1000
          count: 1000
          balance: 112848192

    'get-address-outputs-response-example':
      value:
        data:
          address: 7ed3d67fc7b619e72e588f51fef2379e43e6e9a856635843b3f29aa3a3f1f006
          maxResults: 1000
          count: 2
          outputIds: 
            - 1c6943b0487c92fd057d4d22ad844cc37ee27fe6fbe88e5ff0d20b2233f75b9d0005
            - ed3c3f1a319ff4e909cf2771d79fece0ac9bd9fd2ee49ea6c0885c9cb3b1248c0010

    'get-milestone-by-index-response-example':
      value:
        data:
          milestoneIndex: 15465
          messageId: 7ed3d67fc7b619e72e588f51fef2379e43e6e9a856635843b3f29aa3a3f1f006
          timestamp: '2020-10-06T17:18:40+00:00'
    
  schemas:
    
    'Message':
      properties:
        version:
          type: integer
        parent1:
          type: string
        parent2:
          type: string
        payload:
          oneOf:
            - $ref: '#/components/schemas/Indexation'
            - $ref: '#/components/schemas/Milestone'
            - $ref: '#/components/schemas/Transaction'
        nonce:
          type: string
  
    'Indexation':
      properties:
        type:
          type: integer
        index:
          type: string
        data:
          type: string
    
    'Milestone':
      properties:
        type:
          type: integer
        index:
          type: integer
        timestamp:
          type: integer
        inclusionMerkleProof:
          type: string
        signature:
          type: string
  
    'UTXOInput':
      properties:
        type:
          type: integer
        transactionId:
          type: string
        transactionOutputIndex:
          type: integer
  
    'TransactionEssence':
      properties:
        type:
          type: integer
        inputs:
          type: array
          items:
            anyOf:
              - $ref: '#/components/schemas/UTXOInput'
        outputs:
          type: array
          items:
            anyOf:
              - $ref: '#/components/schemas/SigLockedSingleOutput'
        payload:
          oneOf:
            - $ref: '#/components/schemas/Indexation'
          nullable: true

    'Transaction':
      properties:
        type:
          type: integer
        essence:
          type: object
          oneOf:
            - $ref: '#/components/schemas/TransactionEssence'
        unlockBlocks:
          type: array
          items:
            anyOf:
              - $ref: '#/components/schemas/SignatureUnlockBlock'
              - $ref: '#/components/schemas/ReferenceUnlockBlock'

    'SignatureUnlockBlock':
      properties:
        type:
          type: integer
        signature:
          type: object
          oneOf:
            - $ref: '#/components/schemas/Ed25519Signature'

    'ReferenceUnlockBlock':
      properties:
        type:
          type: integer
        reference:
          type: integer

    'Ed25519Address':
      properties:
        type:
          type: integer
        address:
          type: string

    'Ed25519Signature':
      properties:
        type:
          type: integer
        address:
          type: string

    'SigLockedSingleOutput':
      properties:
        type:
          type: integer
        address:
          anyOf:
            - $ref: '#/components/schemas/Ed25519Address'
        amount:
          type: integer
  
    'ErrorResponse':
      properties:
        error:
          type: object
          properties:
            code:
              type: string
            message:
              type: string

    'BadRequestErrorResponse':
      allOf:
        - $ref: '#/components/schemas/ErrorResponse'
      example:
        error:
          code: "invalid_data"
          message: invalid data provided

    'NotFoundErrorResponse':
      allOf:
        - $ref: '#/components/schemas/ErrorResponse'
      example:
        error:
          code: "not_found"
          message: could not find data
  
    'GetInfoResponse':
      properties:
        data:
          type: object
          properties:
            name:
              type: string
            version:
              type: string
            isHealthy:
              type: boolean
            coordinatorPublicKey:
              type: string
              format: binary
            latestMilestoneMessageId:
              type: string
            latestMilestoneIndex:
              type: integer
            solidMilestoneMessageId:
              type: string
            solidMilestoneIndex:
              type: integer
            pruningIndex:
              type: integer
            features:
              type: array
              items:
                type: string
  
    'GetTipsResponse':
      properties:
        data:
          type: object    
          properties:
            tip1:
              type: string
            tip2:
              type: string

    'PostMessagesResponse':
      properties:
        data:    
          type: object    
          properties:        
            messageId:
              type: string

    'GetMessagesByIndexResponse':
      properties:
        data:    
          type: object    
          properties:  
            index:
             type: string
            maxResults:
             type: integer
            count:
             type: integer
            messageIds:
             type: array
             items:
               type: string

    'GetMessageMetadataByIdResponse':
      properties:
        data:
          type: object    
          properties:
            messageId:
              type: string
            parent1MessageId:
              type: string
            parent2MessageId:
              type: string
            isSolid:
              type: boolean
            referencedByMilestone:
              type: integer
              nullable: true
            ledgerInclusionState:
              enum: 
                - included
                - conflicting
            shouldPromote:
              type: boolean
            shouldReattach:
              type: boolean
          required:
            - messageId
            - parent1MessageId
            - parent2MessageId
            - solid
            - referencedByMilestone

    'GetMessageByIdDataResponse':
      properties:
        data:
          type: object
          properties:
            allOf:
              $ref: '#/components/schemas/Message'
  
    'GetMessageChildrenResponse':
      properties:
        data:
          type: object    
          properties:
            messageId:
              type: string
            maxResults:
              type: integer
            count:
              type: integer
            children:
              type: array
              items:
                type: string

    'GetOutputsByIdResponse':
      properties:
        data:
          type: object
          properties:
            messageId:
              type: string
            transactionId:
              type: string
            outputIndex:
              type: integer
            isSpent:
              type: boolean
            output:
              anyOf:
                - $ref: '#/components/schemas/SigLockedSingleOutput'

    'GetAddressBalanceResponse':
      properties:
        data:
          type: object    
          properties:
            address:
              type: string
            maxResults:
              type: integer
            count:
              type: integer
            balance:
              type: integer
  
    'GetAddressOutputsResponse':
      properties:
        data:
          type: object    
          properties:
            address:
              type: string
            maxResults:
              type: integer
            count:
              type: integer              
            outputIDs:
              type: array
              items: 
                type: string

    'GetMilestoneByIndexResponse':
      properties:
        data:
          type: object
          properties:
            milestoneIndex: 
              type: integer
            messageId:
              type: string
            timestamp:
              type: string
              description: Timestamp in RFC3339
